### ISSUE TITLE
Insole model

### ISSUE THREAD

**Issue by mysablehats** [Huawei-UTwente/BioMechPro-WearableSystemValidation#1]
It is more of a general question, but what is the Insole model from Moticon that you use in this dataset? Or maybe it doesn't matter?

Also the permissions on the bitbucket original repo are set to private, I think.

**Comment by HuaweiWang** [comment]
Hi @mysablehats,

We used the Moticon Insole3 for this experimental recording. The data format may be different will different versions of moticon insoles (or the SDK verison, we used SDK_03.00.00 for this recording). Also check this [repo](https://github.com/HuaweiWang/WearableMeasurementSystem) to understand how we parsed the insole data to .txt file.

If you have a different insole data structure saved, adjusting the insole loading module in this pipeline to load the correct Fy and CoP information is another option.

Thanks for the feedback about the bitbucket link. I included them in my OneDrive and you should be able to access now.

Best,
Huawei
